package: module_preview
version: '1.3.0'
author: 'Friends Of REDAXO'

page:
  title: Module preview
  perm: admin[]
  icon: rex-icon fa-th
  subpages:
    settings: { title: translate:settings }
    modules: { title: translate:manage_images }

requires:
  redaxo: ^5.7.0
  php:
    version: '>=7.4'

installer_ignore:
  - node_modules
  - .git
  - .gitignore
  - .github
  - tests
  - .tools
  - package.json
  - yarn.lock
  - resources
  - .editorconfig
  - .eslintrc.js
  - .stylelintrc.js
  - phpcs.xml
  - phpunit.xml.dist
  - composer.json
  - composer
  - composer.lock
