package: module_preview
version: '1.2.0'
author: 'Friends Of REDAXO'

page:
  title: Module preview
  perm: admin[]
  icon: rex-icon fa-th
  subpages:
    settings: { title: translate:settings }
    modules: { title: translate:manage_images }

requires:
  redaxo: ^5.7.0
  php:
    version: '>=7.1'
