package: module_preview
version: '1.0.0'
author: eaCe

page:
  title: Module preview
  perm: admin[]
  icon: rex-icon fa-th
  subpages:
    settings: { title: translate:settings }

requires:
  redaxo: ^5.7.0
  php:
    version: '>=7.1'
